### ISSUE TITLE
UserFilter and CommentFilter

### ISSUE THREAD

**Issue by dereklopes** [jennifernghi/SVCEbackend#1]
I'm currently deploying to a server. I suggest not updating until we get this figured out.

Line 11 in views.py:
from filters import CommentFilter, UserFilter

I'm getting an import error after running "./manage.py migrate" in my virtualenv saying CommentFilter and UserFilter are not defined and cannot be imported. I can remove the import and just import everything from filters but that just leaves me with a NameError because CommentFilter is not defined.

I can't find any documentation on these imports. Where are they defined?

**Comment by jennifernghi** [comment]
i am guessing that you may missing installs, try to install all packages in requirements.txt in your virtual environment

appdirs==1.4.3
awsebcli==3.10.0
backports.ssl-match-hostname==3.5.0.1
blessed==1.14.1
botocore==1.5.26
cement==2.8.2
colorama==0.3.7
Django==1.9
django-filter==1.0.1
djangorestframework==3.6.2
docker-py==1.7.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.13.1
jmespath==0.9.2
MySQL-python==1.2.5
packaging==16.8
pathspec==0.5.0
pyparsing==2.2.0
python-dateutil==2.6.0
PyYAML==3.12
requests==2.9.1
semantic-version==2.5.0
six==1.10.0
tabulate==0.7.5
termcolor==1.1.0
wcwidth==0.1.7
websocket-client==0.40.0

**Comment by dereklopes** [comment]
I fixed it by using python 2.7 instead of 3.4, thanks
